# Generated by Django 5.2.8 on 2025-11-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
