apiVersion: v1
kind: Service
metadata:
  name: drf-api-service
spec:
  selector:
    app: drf-api
  ports:
    - port: 8000        # Service port
      targetPort: 8000 # Container port
  type: NodePort
